node: CP*
coding_query:

2: {
ALLOT: (IP* iDoms V*) AND (V* iDoms allotted|allot|alloted|allott|allotting|allotts)
APPOINT: (IP* iDoms V*) AND (V* iDoms apoynteth|appoint|appointed|appointeth|appoynte|appoynted|a-poynt|a-poyntyd|apoint|apointed|apointes|apointinge|apoyented|apoyentyd|apoynt|Apoynt|apoynte|apoynted|apoyntid|apoynttyd|apoyntyd|apoyntyde|appoinct|appoincte|appoincted|APPOINCTED|appoinnted|Appoint|$appoint|appointe|$appointed|APPOINTED|Appointed|appointede|appointid|appointide|appointing|appoints|appointt|appointteth|appoi~tyd|appoointed|appoyncted|appoyneted|appoynt|Appoynte|appoyntes|appoynteth|appoyntid|appoynting|appoynts|appoyntte|appoyntyd|appoyntyde|appoyntyng)
ASSIGN: (IP* iDoms V*) AND (V* iDoms assign'd|assigne|assigned|a-signyd|a-sygne|a-sygnyd|asigne|asigned|asine|asined|assign|ASSIGNED|Assigned|assignede|assigneed|assignet|assigneth|assigning|assigns|assygne|assygned|assygneth|assygnid|assygnyd|assygnyde|assyne|assyned|assyngne|assyngned|assyngnyd|assynyd|asygne|asygnyd|asyne|asyngne)
AYEVEN: (IP* iDoms V*) AND (V* iDoms a+gaef|a+gaf|a+gef|a+gefe|a+gefen|a+geoue|a+gif|a+giue+d|a-+gef|a+geouen|a+geuen|a-+geuen)
BEQUEATH: (IP* iDoms V*) AND (V* iDoms bequeth|bequethyd|becwe+d|bequeath|bequeath'd|bequeathed|bequeathest|bequeathing|beqwathe|bi-que+de|bi-que+t|$bi-que+t|biqua+t|bique+d|bique+de)
BEHIEGHT: (IP* iDoms V*) AND (V* iDoms be-hated|be-hiet|be-hoote|be-hote|be-hygth|be-hyte|behat|behaten|behatst|beheet|beheght|behet|behete|behette|behiet|behighte|behite|behot|behote|behote+d|behote+t|behoten|behotynge|behyght|behyte|$behyte|beieton|bi-hat|bi-haten|bi-hehte|bi-het|bi-hete|bi-hoten|bihat|bihate|bihate+d|bihatede|bihaten|$bihaten|biheeten|bihet|bihete|biheten|biheteth|bihetith|bihi+gt|bihi+gte|bihi+gten|bihight|bihooteth|bihote|bihoten|byheet|byheeten|byhet|byhetu+t|byhi+gt|byhi+gte|byhoot|byhote|byhote+t|byhyght|bihahte|Bihat)
BETAKE: (IP* iDoms V*) AND (V* iDoms beo-take|betake|betake+t|betaken|betakenande|betakens|betakynde|betakyns|betoke|betook|betooke|bitake|bitaken|bitakith|bitakun|bitoke|bitook|by-took|bytook|[bi-tok]|be-toke|bytak|bytake|bytakins)
CARRY: (IP* iDoms V*) AND (V* iDoms carrie|carry|cari|carid|carie|caried|Caried|carien|carieng|caries|carieth|carri|carri'd|carried|Carried|$carried|carries|carriest|carrieth|carring|Carry|$carry|carry'd|carry's|carryd|carrye|carryed|carryeng|carryes|carryeth|carrying|CARRYING|Carrying|carryinge|carryng|carrys|cary|Cary|caryd|carye|Carye|caryed|Caryed|caryen|caryes|caryeth|caryid|carying|caryinge|caryith|carys|caryth)
DELIVER: (IP* iDoms V*) AND (V* iDoms dalyvered|de-liuer|de-liuere|deleuer|deleuered|deleverd|deleverde|delevered|delibered|delieuered|delievered|deliuer|Deliuer|deliuer'd|deliuerd|deliuere|$deliuere|deliuere+t|deliuered|$deliuered|deliuerede|deliueredest|deliueret|deliuereth|$deliuerid|deliuerid|deliueride|deliuering|deliuers|deliueryd|deliueryng|deliuir|deliuirs|deliure|deliured|deliurede|deliuri|deliurid|deliu~d|deliv=r=|deliv=r=ed|delived|deliver|Deliver|$deliver|deliver'd|deliverd|deliverde|delivere|delivered|$delivered|Delivered|deliverede|deliveret|delivereth|deliverid|delivering|deliverit|delivers|delivery|deliveryd|delivre|delivred|delivrid|dellyver|dellyveryd|delueryd|delyered|delyuer|Delyuer|$delyuer|delyuerd|delyuerde|delyuere|$delyuere|delyuere`|delyuered|$delyuered|delyuerede|DELYUEREDE|$delyuerede|delyueren|delyuereth|delyuerid|delyueriden|delyuering|delyuers|delyuert|delyueryd|$delyueryd|delyuerydd|delyueryn|delyure|delyured|delyuri|delyury|delyuyr|Delyuyr|delyuyrd|delyuyrdd|delyuyrt|delyuy~|delyu~|delyu~ed|delyu~yd|delyvared|delyved|delyver|Delyver|delyverd|delyverde|delyvere|delyvered|$delyvered|delyverede|delyverid|delyvering|delyvers|delyvery|delyveryd|delyveryde|delyveryed|delyveryt|delyveyred|delyvird|delyvirde|delyvrd|delyvrde|delyvred|delyvyrd|delyvyred|delyvyrte|delyv~|delyv~ed|delywer|delywirdd|delywyrd|deyuered|diliuere|diliueren|diliver|dilivered|dilyuered|dilyuerede|dilyver|dyllyu~d|dylyuered|dylyueryd|y-dylyveryd|delliver|dellivered)
FEED: (IP* iDoms V*) AND (V* iDoms feede|feeds|fed|fedan|fedd|fedde|fedden|feddenn|feddest|fede|fede+d|fede+t|fede+t+t|feden|fedenn|fedes|fedest|fedeth|fedi+t|feding|fedis|fedith|fedon|fedu+t|fedy+t|fedynge|feed|Feed|feed'st|feedd|feeden|feedes|feedeth|feeding|feedyth)
GIVE: (IP* iDoms V*) AND (V* iDoms +g+afe|+g+afenn|+g[a]f|+gaef|+gaf|+gafe|+gaff|+Gaff|+gaif|+gaue|+gauen|+gauest|+gave|+gavf|+gavfe|+geaue|+gef|+Gef|$+gef|+gefe|+gefe+d|+gefen|+gefuen|+geoue|+geoue+d|+geouen|+geuan|+geuand|+geue|+Geue|+geue+d|+geue+de|+geue+t|+geuen|$+geuen|+geuest|+geueth|+geuon|+geuyn|+geuyng|+geuynge|+geuyst|+geuyth|+geve|+geve+t|+gevyn|+gevyng|+gevyth|+geyfe|+gieu|+gieuene|+gif|+Gif|+gif+d|+gif+de|+gifand|+gife|+gife+d|+gife+t|+gife+t+t|+gifen|+gifenn|+giff|+gifst|+gift|+gifue|+gifuen|+gifuest|+giue|+giue+d|+giue+de|+giue+t|+giuen|+giuene|+giuest|+giueth|+giuing|+give|+goue|+gouen|+Gouen|+goun|+gouon|+gouun|+gouyn|+gove|+goven|+Goven|+govyn|+gyeu+t|+gyf|+Gyf|+gyfe|+gyue|+Gyue|+gyue+t|+gyuen|+gyueth|+gyuynge|+gyuyngge|+gyvyngge|g+af|g+afenn|ga|gaave|gaf|gafe|gaff|gaffe|gau'st|gaue|Gaue|$gaue|gauest|gav|gave|$gave|gaveffe|gavest|gawe|gayff|geaf|geauen|geave|geaven|geeue|geeuen|geeueth|geeve|geeven|geeveth|geevf|geeving|gef|gefe|gefeyng|geff|geffe|geffun|geffyn|geiue|geiuen|geiueth|geive|geiven|geu|geue|Geue|$geue|geuen|geuende|geues|geueth|geuethe|geue~|geufe|geuin|geuing|Geuing|geuinge|geuith|geunne|geuyn|geuyng|geuynge|geuyst|geuyth|gev|geve|Geve|geven|Geven|gevene|geves|geveth|gevethe|geve~|gevff|gevin|geving|gevinge|gevith|gevyn|gevyne|gevyng|gevynge|gevyth|gevythe|geyf|geyfe|geyff|ghye|giaf|gief|gieuen|gieve|gif|Gif|gif+d|gife|gife+d|gife+t+t|gifen|gifenn|gifes|giff|giffe|giffen|giffeth|giffyn|giude|giue|Giue|giue+d|giue-'a|giued|giueing|giueinge|giuen|Giuen|GIUEN|giuende|giuent|giues|giueth|giue~|giuin|giuing|giuinge|giuis|giv|giv'n|giv's|give|Give|$give|GIVE|giveing|giveinge|given|Given|$given|givene|giveng|gives|Gives|givest|giveth|givethe|give~|givin|giving|Giving|givinge|Givinge|givith|givn|givne|givynge|goue|gouyn|gove|goven|govyn|govynge|gyf|Gyf|gyf+d|gyfe|gyfen|gyfes|gyff|gyffe|Gyffe|gyffen|gyffene|gyffes|Gyffes|gyffez|gyffin|gyffvyn|gyffyn|gyffyne|gyffyng|gyffynge|gyffyth|gyfs|gyue|GYUE|gyuen|gyueth|gyuing|gyuyn|gyuynge|gyve|gyvede|gyven|gyvene|gyveng|gyvenge|gyves|gyveth|gyvethe|gyving|gyvne|gyvyn|gyvyng|gyvynge|i+af|i+afen|i+gefen|i+gefuen|i+geue|i+geuen|i+giuen|i+goue|i+gyue|i-+geve|i-+gove|i-gyved|i-yeve|iauen|igeue|iyeven|iyue|y+geue|y+giue|y+gyue|y-yeue|y-yeuen|y-yeve|yaf|yafe|yaff|yaffe|yaue|yave|yaven|yeaf|yeaff|yeave|yef|yef+t|yeff|yeffe|yeffyn|yefst|yeft|yeoven|Yeoven|yeue|$yeue|yeue+t|yeuen|Yeuen|$yeuene|yeueth|yeuyng|yeve|yeven|Yeven|yevest|yeveth|yeving|yevith|yevyn|yevynge|yif|yiuen|yive|youe|youen|Youen|youse|youyn|yove|yoven|Yoven|yovyn|yue|yue+t|yyeue|+gief+d|+gieue|+gieue+d|+gieuen|+Giuen|Gave|$gawe|gayffe|gibe|i+giue|iaf|iafen|yves|yveue)
GRANT: (IP* iDoms V*) AND (V* iDoms g=a=unted|grant|Grant|$grant|grante|grante+t|granted|grantede|granten|granti|granting|GRANTING|grants|granttyd|grantyd|graund|graunt|Graunt|grauntd|graunte|Graunte|$graunte|graunte+t|graunted|grauntede|graunten|grauntes|$grauntest|graunteth|graunti+t|grauntid|grauntide|graunting|grauntith|grauntted|graunttid|graunttide|graunttyd|grauntud|grauntude|graunty+te|grauntyd|grauntyde|grauntynge|grauntyth|grau~t|grau~te|grau~ted|grau~tyd|gravnte|$grawnt|grawnt|grawnte|grawnted|grawntethe|grawntid|grawnty|grawntyd|$grawntyn|grawntyn|grawntyng|grawntyth|i-graunted|y-granted|y-graunted|$y-graunted|ygraunted|grannt|Granted|granteid|grantid|granttyde|grantyt|igraunted)
LEND: (IP* iDoms V*) AND (V* iDoms lend|Lend|lende|lent|lente|y-lend|lended|lendenn|lendest|lendeth|lending|Lending|lends|lendyn|$lent|Lent|lentte|ylend)
OFFER: (IP* iDoms V*) AND (V* iDoms i-offrad|i-offrede|ofer|offeaaret|offeare|offeared|offearen|offearet|offer|Offer|offer'd|offerand|offerd|offerde|offered|$offered|offeren|offeres|offereth|offerid|offeride|offering|Offering|offeringe|offerist|offerith|offern|offerne|offerr|offerred|offerryd|offers|Offers|offert|offerthe|offeru+t|offeruht|offeryd|offeryn|offeryng|offerynge|offeryth|offe~ded|offir|offird|offireth|offirs|Offirs|offor|offre|Offre|offre+d|offre+t+t|offred|offredd|Offredd|offredde|offrede|offreden|offredon|offren|offrenn|Offrenn|offresst|offrest|offreth|offrethe|offri|offri+d|offrian|offrid|offride|offriden|offrien|offrin|offring|offringe|offryd|offryng|offrynge|offurred|offyr|offyrd|offyrde|offyryng|ofrid|ofyrd|y-offered|ofers|off+ared|offar|ioffred|ioffret)
OWE: (IP* iDoms V*) AND (V* iDoms $old|ow|ow'd|ow's|ow'st|owd|owe|Owe|owe+t|owed|oweden|oweing|oweinge|owen|oweng|owes|owest|oweth|owhte|owing|owinge|owinges|owith|owte|owyd|owyth|owythe|oxe+t|oxi|Owed|owghe|owght|owghte|Owing|owt|owth)
PAY: (IP* iDoms V*) AND (V* iDoms p=d=|p=d=.|pai|pai+ge|pai+ge+d|pai+gede|pai+gen|pai+get|paid|Paid|paide|paie|paied|paiede|paieing|paieinge|paien|paieng|paies|paieth|paijd|painge|paiyinge|paiyng|pay|$pay|Pay|pay'|pay'd|pay'ing|pay+t|payand|payd|$payd|payde|paye|PAYE|paye+t|payed|Payed|payede|payeden|payee|payeid|payen|payeng|payenge|payes|payet|payeth|payethe|payeyd|payid|paying|payinge|payng|pays|payth|payyd|pd|pd.|pd~|y-payd|y-payde|ypayd|ipaiet|payeing|Payes|peyse)
PROFFER: (IP* iDoms V*) AND (V* iDoms profer|proffer'd|profferyd|profferyng|proffer|profferd|proffered|provfferdi-profred|proferede|profre|profred|proferd|profered|proferet|proferid|profering|proferith|proferre|proferred|proferrid|proferryd|profers|profert|proferyd|proferyth|profrede|profreden|profren|profri+t|p~fer|p~ferred|p~ferryd|p~feruth)
PROMISE: (IP* iDoms V*) AND (V* iDoms promis'd|promisd|promise|promised|promising|promyse|promysed|promysyd|promysyng|p~myse|p~mytt|y-promesed|p'mise|p'mised|premis'd|premise|premised|premisyd|promes|promesed|promesse|promessed|promest|promesyd|promies|promis|Promise|$promised|Promised|promiseing|promises|promisest|promiseth|promisethe|promisheth|promisid|promiside|promisinge|promisith|promiss|promissd|promisse|promissed|promisses|promisseth|promissethe|promissid|promist|promisyde|promitte|promittet|promittyd|promittyng|prommessid|prommyssid|promyce|promys|promyseid|promyses|promyseth|promyseyd|promysid|promysing|promysith|promysse|promyssyd|promyst|promysyde|promysynge|promysys|promysyth|promytte|promytted|$promytted|promyttid|promyttyd|promyttyng|p~mise|p~mised|p~miseth|p~mising|p~miss|p~miss'd|p~mitt|p~mitted|p~mitting|p~mitt~|p~mysyd)
RESTORE: (IP* iDoms V*) AND (V* iDoms restoore|restore|restored|restoored|restor'd|restord|restorde|Restore|Restored|restorede|restoreing|restoren|restores|restoreth|restorid|restoride|restoring|restoryd|restoryng|restowred)
RETURN: (IP* iDoms V*) AND (V* iDoms return|return'd|returne|returned|retourn|retournd|retourne|Retourne|retourned|retournede|retournen|retournes|retourneth|retournid|retourning|retournith|retournyd|retournyng|retovrne|retowrned|retturne|retuerning|Return|returnd|returnde|Returne|$returned|Returned|returneing|returnen|returnes|returnest|returneth|returnid|returning|Returning|returninge|returns|returnyd|returnyde|returnyng)
SELL: (IP* iDoms V*) AND (V* iDoms salde|salden|sel|selde|selden|seldest|sell|Sell|selle|selle+d|sellen|sellenn|selleth|sellethe|sellid|selling|sellinge|sells|sellyd|sellyn|sellyng|sellys|sellyth|sold|solde|soold|ssel|sselt|zel+t|zelle|zelle+t|zold|isold)
SEND: (IP* iDoms V*) AND (V* iDoms i-send|i-sende|i-sent|i-sente|isend|isende|isent|isente|saende|seand|seande|send|Send|SEND|$send|send's|send-a|sendan|sendand|sendd|sendde|sende|Sende|$sende|sende+d|sende+t|sendedst|sendeing|senden|sendes|sendest|sendeth|$sendeth|sendethe|sendi+t|sending|Sending|SENDING|sendinge|sendis|sendith|sends|sendt|sendyd|sendyn|sendyng|sendynge|sendys|sendyt|sendyth|sendythe|sennde|sennde+t+t|sennt|sent|SENT|$sent|Sent|sente|Sente|senten|sentest|sentt|sentte|sentyn|sentyst|ssende|zend|zende|zent|zente|zentest|seend|seende|seending)
SERVE: (IP* iDoms V*) AND (V* iDoms i-served|iserued|serrfenn|serrvenn|seru'd|Seru'd|serue|Serue|SERUE|serue+d|Serue+d|serue+t|Serue+t|serued|seruede|serueden|seruen|SERUEN|serues|seruest|seruet|serueth|Serueth|serui|serui+d|$serui+d|serui+t|seruid|seruide|seruin|seruing|seruis|seruist|seruon|seruy+t|seruyd|$seruyd|seruyde|seruyden|seruyn|seruyng|seruys|seruyth|serv|serv'd|serv's|serve|Serve|serve+t|served|$served|servede|serveing|serven|serves|serveth|servi|servid|serving|Serving|servist|servith|servyd|servydde|servyde|servyng|servynge|serwyd|seryf|y-serued|y-served|yserued|i-servyd)
SHOW: (IP* iDoms V*) AND (V* iDoms $+ateowde|+ateowde|i-sceawed|i-schewed|iscawed|isceawe+d|isceawed|ischawed|ischawet|scawe|scawede|sceaude|sceawe+d|sceawede|sceawen|sceawest|sceawien|sceawin|schaw|schawde|schawdest|schawe|$schawe|schawe+d|$schawe+d|Schawe+d|schawede|schawen|schawest|schawet|schawi|schawi+d|schawin|schcwe|scheaw|scheawe+d|scheuyd|schew|Schew|$schew|schewand|schewande|schewde|schewe|Schewe|schewe+t|$schewe+t|schewed|schewede|$schewede|$schewedest|schewedist|schewedon|schewedyst|schewen|schewes|schewet|scheweth|scheweyt|schewi+t|schewid|schewide|schewiden|schewidist|schewist|schewith|schewod|schewon|schewy+t|schewyd|schewyde|schewyn|schewyng|schewynge|schewyth|schow|schowd|schowe|schowed|schowet|schowide|schowyd|schowyng|sh+awe|sh+awe+t+t|sh+awedd|sh+awenn|Sh+awenn|sh+awesst|shaue|sheaw|sheawe|sheawed|sheawes|sheod|shew|Shew|shew'd|shew'st|shew=d=|shewand|shewd|shewde|shewe|Shewe|$shewe|shewe+d|shewe+t|shewed|Shewed|$shewed|shewede|sheweden|$shewedest|shewedst|shewen|sheweng|shewes|Shewes|shewest|sheweth|shewethe|shewid|Shewid|shewide|shewing|Shewing|SHEWING|shewinge|shewith|shewn|shewne|$shews|shews|shewse|shewthe|shewyd|Shewyd|shewyde|shewying|shewyng|Shewyng|shewynge|shewyt|shewyth|shewythe|sheywyd|show|Show|$show|show'd|show's|showd|showde|showe|showed|showede|showeing|showes|showest|showeth|showid|showing|Showing|showith|shown|showne|shows|showyd|showyng|showynge|y-shewed|yschewet|ysseawed|ischewd|shew's|Shewynge|Shewyth|yschewed)
VOUCHSAFE: (IP* iDoms V*) AND (V* iDoms vouch-safe|vouchsafe|voutsafe|vochesaf|vochsafe|votsafe|vouchafe|vouchafing|vouche-saaf|vouche-safe|vouched-saaf|vouchesaf|vouchesafe|vouchesafed|vouchesafeth|vouchesauf|vouchesave|voucheth-saaf|vouchith-saaf|vouchsaf|Vouchsafe|vouchsafed|vouchsafeing|vouchsafes|vouchsafeth|vouchsaffe|vouchsafing|vouchsaft|vouchsauf|vouchsauff|vouchsavid|voutchesaved|voutchsafe|voutchsaffe|voutsafed|voutsafing|vowche-save|vowchesafe|vowchesaff|vowchesaufe|vowchesave|vowchesawf|woche-saffe|wochesaff|woochsaveffe|wouchesaffe)
YIELD: (IP* iDoms V*) AND (V* iDoms +gald|+galde|+geelde|+geld|+gelde|+Gelde|+gelde+d|+gelde+t|+gelded|+gelden|+geldenn|+geldest|+geldide|+geldyng|+geldynge|+geldyth|+gilde|+gilt|+gold|+golde|+golden|+goldyn|gield|i-+golde|yeald|yealde|yealde+t|yealded|yealdeth|yealdinge|yealdy|yeeld|yeelddid|yeelde|yeelded|yeeldes|yeeldeth|yeelding|YEELDING|yeelds|yeild|yeilded|yeilding|yeildinge|yeld|Yeld|yelde|yelde+t|yelded|yelden|yeldes|yeldeth|yelding|yeldinge|yeldyd|yeldyng|yeldynge|yelt|yheldand|yield|yielded|yielding|yields|yolde|yolden|yuel+t|yueld|+geald|+giald|+gielde|+gielden|geald|yoldyd|yoldyn|yoldynne)
NA: ELSE
}
