library(bbmle)
library(plyr)
load('~/Git/ditransitive-scripts/proposal/newdit.RData')

standardize = function(dataMat){
  m = mean(dataMat)
  sd = sd(dataMat)
  zDataMat = (dataMat-m)/sd
  return(zDataMat)
}

pall<-subset(dit,(Pas=='REC'|Pas=='THEME')&(NVerb=='TELL'|NVerb=='ALLOW'|NVerb=='PROMISE'|NVerb=='GIVE'|NVerb=='TAKE'|NVerb=='BRING'|NVerb=='SEND'|NVerb=='DENY'|NVerb=='THROW'|NVerb=='TEACH'|NVerb=='OLDENG'))
thirt<-subset(pall,YoC<=1350&Pas!='REC')
pall<-as.data.frame(rbind(subset(pall,YoC>1350),thirt))
rm(thirt)
pall$DO<-factor(pall$DO)
pall$IO<-factor(pall$IO)
ball<-subset(pall,IOType=='DP'|IOType=='NoIO')
tall<-subset(pall,IOType!='NoIO'&(NVerb=='PROMISE'|NVerb=='GIVE'|NVerb=='OLDENG'))
basdata<-data.frame(Year=ball$YoC,Value=ball$PasValue,Type=c('BarePassive'),IO=ball$IO,DO=ball$DO)
pasdata<-data.frame(Year=tall$YoC,Value=tall$PPValue,Type=c('ToPassive'),IO=tall$IO,DO=tall$DO)

given<-subset(dit,(NVerb=='PROMISE'|NVerb=='GIVE'|NVerb=='OLDENG')&Pas=='ACT')

given.da<-subset(given,NOrder=='DA')
given.ad<-subset(given,NOrder=='AD')

da <- data.frame(Year=given.da$YoC,Value=given.da$PPValue,Type=c('DA'),IO=given.da$IO,DO=given.da$DO)
ad <- data.frame(Year=given.ad$YoC,Value=given.ad$PPValue,Type=c('AD'),IO=given.ad$IO,DO=given.ad$DO)
joint.data <- as.data.frame(rbind(ad,da,basdata,pasdata))
joint.data$Cond<-joint.data$Type

levels(joint.data$Cond)<-c('1','2','3','4')
joint.data$Cond<-as.numeric(as.character(joint.data$Cond))

joint.data$IO <- factor(joint.data$IO)
joint.data$DO <- factor(joint.data$DO)

joint.data$iosum <- factor(joint.data$IO)
levels(joint.data$iosum) <- c(-1,1)
joint.data$iosum<-as.numeric(as.character(joint.data$iosum))

joint.data$dosum <- factor(joint.data$DO)
levels(joint.data$dosum) <- c(-1,1)
joint.data$dosum<-as.numeric(as.character(joint.data$dosum))

joint.data$iopro <- factor(joint.data$IO)
levels(joint.data$iopro) <- c(0,1)
joint.data$iopro<-as.numeric(as.character(joint.data$iopro))

joint.data$donoun <- factor(joint.data$DO)
levels(joint.data$donoun) <- c(1,0)
joint.data$donoun<-as.numeric(as.character(joint.data$donoun))

joint.data$dopro <- factor(joint.data$DO)
levels(joint.data$dopro) <- c(0,1)
joint.data$dopro<-as.numeric(as.character(joint.data$dopro))

joint.data$iodo <- joint.data$iopro*joint.data$dopro

real.data<-data.frame(Year=joint.data$Year,x=standardize(joint.data$Year),y=joint.data$Value,cond=joint.data$Cond,iosum=joint.data$iosum,iopro=joint.data$iopro,iodo=joint.data$iodo,donoun=joint.data$donoun)

real.data$is.to <- factor(real.data$cond)
levels(real.data$is.to)<-c('1','1','0','1')
real.data$is.to<-as.numeric(as.character(real.data$is.to))

real.data$is.acc <- factor(real.data$cond)
levels(real.data$is.acc)<-c('0','1','1','0')
real.data$is.acc<-as.numeric(as.character(real.data$is.acc))

real.data$acc.sum <- factor(real.data$cond)
levels(real.data$acc.sum)<-c('0','-1','1','0')
real.data$acc.sum<-as.numeric(as.character(real.data$acc.sum))

real.data$is.da <- factor(real.data$cond)
levels(real.data$is.da)<-c('0','1','0','0')
real.data$is.da<-as.numeric(as.character(real.data$is.da))
real.data$is.ad <- factor(real.data$cond)
levels(real.data$is.ad)<-c('1','0','0','0')
real.data$is.ad<-as.numeric(as.character(real.data$is.ad))
real.data$not.ad <- factor(real.data$cond)
levels(real.data$not.ad)<-c('0','1','1','1')
real.data$not.ad<-as.numeric(as.character(real.data$not.ad))

data1<-subset(real.data,cond==1)
data2<-subset(real.data,cond==2&donoun==1)
data3<-subset(real.data,cond==3&donoun==1)
data4<-subset(real.data,cond==4)

true.data<-as.data.frame(rbind(data1,data2,data3,data4))

Order1500 <- margin.table(table(subset(joint.data,(Type=='AD'|Type=='DA')&Year>1500&IO=='IONoun'&DO=='DONoun')$Type))
AD1500 <- margin.table(table(subset(joint.data,Type=='AD'&Year>1500&IO=='IONoun'&DO=='DONoun')$Type))
ord = (Order1500-AD1500)/Order1500

full_ll<-function(aTo=0,aAcc=0,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,bTo=0,bAcc=0,bToAD=0,bToDA=0,bAccAct=0,bAccPas=0,bToPas=0,gTo=0,gAcc=0,gToAD=0,gToDA=0,gAccAct=0,gAccPas=0,gToPas=0,dTo=0,dAcc=0,dToAD=0,dToDA=0,dAccAct=0,dAccPas=0,dToPas=0,orderTo=0,orderAcc=0,orderToAD=0,orderToDA=0,orderAccAct=0,orderAccPas=0,orderToPas=0){
  p1<-((1-(1-(ord+orderTo+orderToAD))*data1$iodo)/(1+exp(-(aTo+aToAD+(bTo+bToAD)*data1$x+(gTo+gToAD)*data1$iosum+(dTo+dToAD)*data1$x*data1$iosum))))
  p2<-((1-(1-(ord+orderTo+orderToDA))*data2$iodo)/(1+exp(-(aTo+aToDA+(bTo+bToDA)*data2$x+(gTo+gToDA)*data2$iosum+(dTo+dToDA)*data2$x*data2$iosum))))*
    ((1-(1-(ord+orderAcc+orderAccAct))*data2$iopro)-((1-(1-(ord+orderAcc+orderAccAct))*data2$iopro)/(1+exp(-(aAcc+aAccAct+(bAcc+bAccAct)*data2$x+(gAcc+gAccAct)*data2$iosum+(dAcc+dAccAct)*data2$x*data2$iosum)))))*data2$donoun
  p3<-((1-(1-(ord+orderAcc+orderAccPas))*data3$iopro)/(1+exp(-(aAcc+aAccPas+(bAcc+bAccPas)*data3$x+(gAcc+gAccPas)*data3$iosum+(dAcc+dAccPas)*data3$x*data3$iosum))))*data3$donoun
  p4<-((1-(1-(ord+orderTo+orderToPas))*data4$iopro)/(1+exp(-(aTo+aToPas+(bTo+bToPas)*data4$x+(gTo+gToPas)*data4$iosum+(dTo+dToPas)*data4$x*data4$iosum))))
  sum1<--sum(stats::dbinom(data1$y, 1, p1,log=TRUE))
  sum2<--sum(stats::dbinom(data2$y, 1, p2,log=TRUE))
  sum3<--sum(stats::dbinom(data3$y, 1, p3,log=TRUE))
  sum4<--sum(stats::dbinom(data4$y, 1, p4,log=TRUE))
  results<-sum(sum1,sum2,sum3,sum4) 
  if (is.finite(results)) { 
    if (is.nan(results)){
      results=NA
      
    }
  }
  else{
    results=NA
  } 
  results
}

fita2b2g2d2o2<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                 bTo=3.9,bAcc=2.7,bToAD=0,bToDA=0,bAccAct=0,bAccPas=0,bToPas=0,
                                 gTo=-1.4,gAcc=-.7,gToAD=0,gToDA=0,gAccAct=0,gAccPas=0,gToPas=0,
                                 dTo=0,dAcc=0,dToAD=0,dToDA=0,dAccAct=0,dAccPas=0,dToPas=0,
                                 orderTo=0,orderAcc=0,
                                 orderToAD=0,orderToDA=0,orderAccAct=0,orderAccPas=0,orderToPas=0),
              control=list(trace=4,REPORT=5,maxit=1000))

fita1b2g2d2o2<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,
                                       bTo=3.9,bAcc=2.7,bToAD=0,bToDA=0,bAccAct=0,bAccPas=0,bToPas=0,
                                       gTo=-1.4,gAcc=-.7,gToAD=0,gToDA=0,gAccAct=0,gAccPas=0,gToPas=0,
                                       dTo=0,dAcc=0,dToAD=0,dToDA=0,dAccAct=0,dAccPas=0,dToPas=0,
                                       orderTo=0,orderAcc=0,
                                       orderToAD=0,orderToDA=0,orderAccAct=0,orderAccPas=0,orderToPas=0),
                    control=list(trace=4,REPORT=5,maxit=1000))

fita2b1g2d2o2<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,bAcc=2.7,
                                       gTo=-1.4,gAcc=-.7,gToAD=0,gToDA=0,gAccAct=0,gAccPas=0,gToPas=0,
                                       dTo=0,dAcc=0,dToAD=0,dToDA=0,dAccAct=0,dAccPas=0,dToPas=0,
                                       orderTo=0,orderAcc=0,
                                       orderToAD=0,orderToDA=0,orderAccAct=0,orderAccPas=0,orderToPas=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2b2g1d2o2<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,bAcc=2.7,bToAD=0,bToDA=0,bAccAct=0,bAccPas=0,bToPas=0,
                                       gTo=-1.4,gAcc=-.7,
                                       dTo=0,dAcc=0,dToAD=0,dToDA=0,dAccAct=0,dAccPas=0,dToPas=0,
                                       orderTo=0,orderAcc=0,
                                       orderToAD=0,orderToDA=0,orderAccAct=0,orderAccPas=0,orderToPas=0),
                             control=list(trace=4,REPORT=5,maxit=1000))

fita2b2g2d1o2<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,bAcc=2.7,bToAD=0,bToDA=0,bAccAct=0,bAccPas=0,bToPas=0,
                                       gTo=-1.4,gAcc=-.7,gToAD=0,gToDA=0,gAccAct=0,gAccPas=0,gToPas=0,
                                       dTo=0,dAcc=0,
                                       orderTo=0,orderAcc=0,
                                       orderToAD=0,orderToDA=0,orderAccAct=0,orderAccPas=0,orderToPas=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2b2g2d2o1<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,bAcc=2.7,bToAD=0,bToDA=0,bAccAct=0,bAccPas=0,bToPas=0,
                                       gTo=-1.4,gAcc=-.7,gToAD=0,gToDA=0,gAccAct=0,gAccPas=0,gToPas=0,
                                       dTo=0,dAcc=0,dToAD=0,dToDA=0,dAccAct=0,dAccPas=0,dToPas=0,
                                       orderTo=0,orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita1b1g2d2o2<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,
                                       bTo=3.9,bAcc=2.7,
                                       gTo=-1.4,gAcc=-.7,gToAD=0,gToDA=0,gAccAct=0,gAccPas=0,gToPas=0,
                                       dTo=0,dAcc=0,dToAD=0,dToDA=0,dAccAct=0,dAccPas=0,dToPas=0,
                                       orderTo=0,orderAcc=0,
                                       orderToAD=0,orderToDA=0,orderAccAct=0,orderAccPas=0,orderToPas=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita1b2g1d2o2<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,
                                       bTo=3.9,bAcc=2.7,bToAD=0,bToDA=0,bAccAct=0,bAccPas=0,bToPas=0,
                                       gTo=-1.4,gAcc=-.7,
                                       dTo=0,dAcc=0,dToAD=0,dToDA=0,dAccAct=0,dAccPas=0,dToPas=0,
                                       orderTo=0,orderAcc=0,
                                       orderToAD=0,orderToDA=0,orderAccAct=0,orderAccPas=0,orderToPas=0),
                    control=list(trace=4,REPORT=5,maxit=1000))

fita1b2g2d1o2<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,
                                       bTo=3.9,bAcc=2.7,bToAD=0,bToDA=0,bAccAct=0,bAccPas=0,bToPas=0,
                                       gTo=-1.4,gAcc=-.7,gToAD=0,gToDA=0,gAccAct=0,gAccPas=0,gToPas=0,
                                       dTo=0,dAcc=0,
                                       orderTo=0,orderAcc=0,
                                       orderToAD=0,orderToDA=0,orderAccAct=0,orderAccPas=0,orderToPas=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita1b2g2d2o1<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,
                                       bTo=3.9,bAcc=2.7,bToAD=0,bToDA=0,bAccAct=0,bAccPas=0,bToPas=0,
                                       gTo=-1.4,gAcc=-.7,gToAD=0,gToDA=0,gAccAct=0,gAccPas=0,gToPas=0,
                                       dTo=0,dAcc=0,dToAD=0,dToDA=0,dAccAct=0,dAccPas=0,dToPas=0,
                                       orderTo=0,orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2b1g1d2o2<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,bAcc=2.7,
                                       gTo=-1.4,gAcc=-.7,
                                       dTo=0,dAcc=0,dToAD=0,dToDA=0,dAccAct=0,dAccPas=0,dToPas=0,
                                       orderTo=0,orderAcc=0,
                                       orderToAD=0,orderToDA=0,orderAccAct=0,orderAccPas=0,orderToPas=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2b1g2d1o2<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,bAcc=2.7,
                                       gTo=-1.4,gAcc=-.7,gToAD=0,gToDA=0,gAccAct=0,gAccPas=0,gToPas=0,
                                       dTo=0,dAcc=0,
                                       orderTo=0,orderAcc=0,
                                       orderToAD=0,orderToDA=0,orderAccAct=0,orderAccPas=0,orderToPas=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2b1g2d2o1<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,bAcc=2.7,
                                       gTo=-1.4,gAcc=-.7,gToAD=0,gToDA=0,gAccAct=0,gAccPas=0,gToPas=0,
                                       dTo=0,dAcc=0,dToAD=0,dToDA=0,dAccAct=0,dAccPas=0,dToPas=0,
                                       orderTo=0,orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2b2g1d1o2<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,bAcc=2.7,bToAD=0,bToDA=0,bAccAct=0,bAccPas=0,bToPas=0,
                                       gTo=-1.4,gAcc=-.7,
                                       dTo=0,dAcc=0,
                                       orderTo=0,orderAcc=0,
                                       orderToAD=0,orderToDA=0,orderAccAct=0,orderAccPas=0,orderToPas=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2b2g1d2o1<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,bAcc=2.7,bToAD=0,bToDA=0,bAccAct=0,bAccPas=0,bToPas=0,
                                       gTo=-1.4,gAcc=-.7,
                                       dTo=0,dAcc=0,dToAD=0,dToDA=0,dAccAct=0,dAccPas=0,dToPas=0,
                                       orderTo=0,orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2b2g2d1o1<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,bAcc=2.7,bToAD=0,bToDA=0,bAccAct=0,bAccPas=0,bToPas=0,
                                       gTo=-1.4,gAcc=-.7,gToAD=0,gToDA=0,gAccAct=0,gAccPas=0,gToPas=0,
                                       dTo=0,dAcc=0,
                                       orderTo=0,orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita1b1g1d2o2<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,
                                       bTo=3.9,bAcc=2.7,
                                       gTo=-1.4,gAcc=-.7,
                                       dTo=0,dAcc=0,dToAD=0,dToDA=0,dAccAct=0,dAccPas=0,dToPas=0,
                                       orderTo=0,orderAcc=0,
                                       orderToAD=0,orderToDA=0,orderAccAct=0,orderAccPas=0,orderToPas=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita1b1g2d1o2<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,
                                       bTo=3.9,bAcc=2.7,
                                       gTo=-1.4,gAcc=-.7,gToAD=0,gToDA=0,gAccAct=0,gAccPas=0,gToPas=0,
                                       dTo=0,dAcc=0,
                                       orderTo=0,orderAcc=0,
                                       orderToAD=0,orderToDA=0,orderAccAct=0,orderAccPas=0,orderToPas=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita1b1g2d2o1<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,
                                       bTo=3.9,bAcc=2.7,
                                       gTo=-1.4,gAcc=-.7,gToAD=0,gToDA=0,gAccAct=0,gAccPas=0,gToPas=0,
                                       dTo=0,dAcc=0,dToAD=0,dToDA=0,dAccAct=0,dAccPas=0,dToPas=0,
                                       orderTo=0,orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita1b2g1d1o2<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,
                                       bTo=3.9,bAcc=2.7,bToAD=0,bToDA=0,bAccAct=0,bAccPas=0,bToPas=0,
                                       gTo=-1.4,gAcc=-.7,
                                       dTo=0,dAcc=0,
                                       orderTo=0,orderAcc=0,
                                       orderToAD=0,orderToDA=0,orderAccAct=0,orderAccPas=0,orderToPas=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita1b2g1d2o1<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,
                                       bTo=3.9,bAcc=2.7,bToAD=0,bToDA=0,bAccAct=0,bAccPas=0,bToPas=0,
                                       gTo=-1.4,gAcc=-.7,
                                       dTo=0,dAcc=0,dToAD=0,dToDA=0,dAccAct=0,dAccPas=0,dToPas=0,
                                       orderTo=0,orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita1b2g2d1o1<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,
                                       bTo=3.9,bAcc=2.7,bToAD=0,bToDA=0,bAccAct=0,bAccPas=0,bToPas=0,
                                       gTo=-1.4,gAcc=-.7,gToAD=0,gToDA=0,gAccAct=0,gAccPas=0,gToPas=0,
                                       dTo=0,dAcc=0,
                                       orderTo=0,orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2b1g1d1o2<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,bAcc=2.7,
                                       gTo=-1.4,gAcc=-.7,
                                       dTo=0,dAcc=0,
                                       orderTo=0,orderAcc=0,
                                       orderToAD=0,orderToDA=0,orderAccAct=0,orderAccPas=0,orderToPas=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2b1g1d2o1<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,bAcc=2.7,
                                       gTo=-1.4,gAcc=-.7,
                                       dTo=0,dAcc=0,dToAD=0,dToDA=0,dAccAct=0,dAccPas=0,dToPas=0,
                                       orderTo=0,orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2b1g2d1o1<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,bAcc=2.7,
                                       gTo=-1.4,gAcc=-.7,gToAD=0,gToDA=0,gAccAct=0,gAccPas=0,gToPas=0,
                                       dTo=0,dAcc=0,
                                       orderTo=0,orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2b2g1d1o1<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,bAcc=2.7,bToAD=0,bToDA=0,bAccAct=0,bAccPas=0,bToPas=0,
                                       gTo=-1.4,gAcc=-.7,
                                       dTo=0,dAcc=0,
                                       orderTo=0,orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2b1g1d1o1<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,bAcc=2.7,
                                       gTo=-1.4,gAcc=-.7,
                                       dTo=0,dAcc=0,
                                       orderTo=0,orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita1b2g1d1o1<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,
                                       bTo=3.9,bAcc=2.7,bToAD=0,bToDA=0,bAccAct=0,bAccPas=0,bToPas=0,
                                       gTo=-1.4,gAcc=-.7,
                                       dTo=0,dAcc=0,
                                       orderTo=0,orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita1b1g2d1o1<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,
                                       bTo=3.9,bAcc=2.7,
                                       gTo=-1.4,gAcc=-.7,gToAD=0,gToDA=0,gAccAct=0,gAccPas=0,gToPas=0,
                                       dTo=0,dAcc=0,
                                       orderTo=0,orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita1b1g1d2o1<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,
                                       bTo=3.9,bAcc=2.7,
                                       gTo=-1.4,gAcc=-.7,
                                       dTo=0,dAcc=0,dToAD=0,dToDA=0,dAccAct=0,dAccPas=0,dToPas=0,
                                       orderTo=0,orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita1b1g1d1o2<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,
                                       bTo=3.9,bAcc=2.7,
                                       gTo=-1.4,gAcc=-.7,
                                       dTo=0,dAcc=0,
                                       orderTo=0,orderAcc=0,
                                       orderToAD=0,orderToDA=0,orderAccAct=0,orderAccPas=0,orderToPas=0),
                    control=list(trace=4,REPORT=5,maxit=1000))

fita0b2g2d2o2<-mle2(full_ll,start=list(bTo=3.9,bAcc=2.7,bToAD=0,bToDA=0,bAccAct=0,bAccPas=0,bToPas=0,
                                       gTo=-1.4,gAcc=-.7,gToAD=0,gToDA=0,gAccAct=0,gAccPas=0,gToPas=0,
                                       dTo=0,dAcc=0,dToAD=0,dToDA=0,dAccAct=0,dAccPas=0,dToPas=0,
                                       orderTo=0,orderAcc=0,
                                       orderToAD=0,orderToDA=0,orderAccAct=0,orderAccPas=0,orderToPas=0),
                    control=list(trace=4,REPORT=5,maxit=1000))

fita2b0g2d2o2<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       gTo=-1.4,gAcc=-.7,gToAD=0,gToDA=0,gAccAct=0,gAccPas=0,gToPas=0,
                                       dTo=0,dAcc=0,dToAD=0,dToDA=0,dAccAct=0,dAccPas=0,dToPas=0,
                                       orderTo=0,orderAcc=0,
                                       orderToAD=0,orderToDA=0,orderAccAct=0,orderAccPas=0,orderToPas=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2b2g0d2o2<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,bAcc=2.7,bToAD=0,bToDA=0,bAccAct=0,bAccPas=0,bToPas=0,
                                       dTo=0,dAcc=0,dToAD=0,dToDA=0,dAccAct=0,dAccPas=0,dToPas=0,
                                       orderTo=0,orderAcc=0,
                                       orderToAD=0,orderToDA=0,orderAccAct=0,orderAccPas=0,orderToPas=0),
                    control=list(trace=4,REPORT=5,maxit=1000))

fita2b2g2d0o2<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,bAcc=2.7,bToAD=0,bToDA=0,bAccAct=0,bAccPas=0,bToPas=0,
                                       gTo=-1.4,gAcc=-.7,gToAD=0,gToDA=0,gAccAct=0,gAccPas=0,gToPas=0,
                                       orderTo=0,orderAcc=0,
                                       orderToAD=0,orderToDA=0,orderAccAct=0,orderAccPas=0,orderToPas=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2b2g2d2o0<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,bAcc=2.7,bToAD=0,bToDA=0,bAccAct=0,bAccPas=0,bToPas=0,
                                       gTo=-1.4,gAcc=-.7,gToAD=0,gToDA=0,gAccAct=0,gAccPas=0,gToPas=0,
                                       dTo=0,dAcc=0,dToAD=0,dToDA=0,dAccAct=0,dAccPas=0,dToPas=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita0b0g2d2o2<-mle2(full_ll,start=list(gTo=-1.4,gAcc=-.7,gToAD=0,gToDA=0,gAccAct=0,gAccPas=0,gToPas=0,
                                       dTo=0,dAcc=0,dToAD=0,dToDA=0,dAccAct=0,dAccPas=0,dToPas=0,
                                       orderTo=0,orderAcc=0,
                                       orderToAD=0,orderToDA=0,orderAccAct=0,orderAccPas=0,orderToPas=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita0b2g0d2o2<-mle2(full_ll,start=list(bTo=3.9,bAcc=2.7,bToAD=0,bToDA=0,bAccAct=0,bAccPas=0,bToPas=0,
                                       dTo=0,dAcc=0,dToAD=0,dToDA=0,dAccAct=0,dAccPas=0,dToPas=0,
                                       orderTo=0,orderAcc=0,
                                       orderToAD=0,orderToDA=0,orderAccAct=0,orderAccPas=0,orderToPas=0),
                    control=list(trace=4,REPORT=5,maxit=1000))

fita0b2g2d0o2<-mle2(full_ll,start=list(bTo=3.9,bAcc=2.7,bToAD=0,bToDA=0,bAccAct=0,bAccPas=0,bToPas=0,
                                       gTo=-1.4,gAcc=-.7,gToAD=0,gToDA=0,gAccAct=0,gAccPas=0,gToPas=0,
                                       orderTo=0,orderAcc=0,
                                       orderToAD=0,orderToDA=0,orderAccAct=0,orderAccPas=0,orderToPas=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita0b2g2d2o0<-mle2(full_ll,start=list(bTo=3.9,bAcc=2.7,bToAD=0,bToDA=0,bAccAct=0,bAccPas=0,bToPas=0,
                                       gTo=-1.4,gAcc=-.7,gToAD=0,gToDA=0,gAccAct=0,gAccPas=0,gToPas=0,
                                       dTo=0,dAcc=0,dToAD=0,dToDA=0,dAccAct=0,dAccPas=0,dToPas=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2b0g0d2o2<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       dTo=0,dAcc=0,dToAD=0,dToDA=0,dAccAct=0,dAccPas=0,dToPas=0,
                                       orderTo=0,orderAcc=0,
                                       orderToAD=0,orderToDA=0,orderAccAct=0,orderAccPas=0,orderToPas=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2b0g2d0o2<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       gTo=-1.4,gAcc=-.7,gToAD=0,gToDA=0,gAccAct=0,gAccPas=0,gToPas=0,
                                       orderTo=0,orderAcc=0,
                                       orderToAD=0,orderToDA=0,orderAccAct=0,orderAccPas=0,orderToPas=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2b0g2d2o0<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       gTo=-1.4,gAcc=-.7,gToAD=0,gToDA=0,gAccAct=0,gAccPas=0,gToPas=0,
                                       dTo=0,dAcc=0,dToAD=0,dToDA=0,dAccAct=0,dAccPas=0,dToPas=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2b2g0d0o2<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,bAcc=2.7,bToAD=0,bToDA=0,bAccAct=0,bAccPas=0,bToPas=0,
                                       orderTo=0,orderAcc=0,
                                       orderToAD=0,orderToDA=0,orderAccAct=0,orderAccPas=0,orderToPas=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2b2g0d2o0<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,bAcc=2.7,bToAD=0,bToDA=0,bAccAct=0,bAccPas=0,bToPas=0,
                                       dTo=0,dAcc=0,dToAD=0,dToDA=0,dAccAct=0,dAccPas=0,dToPas=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2b2g2d0o0<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,bAcc=2.7,bToAD=0,bToDA=0,bAccAct=0,bAccPas=0,bToPas=0,
                                       gTo=-1.4,gAcc=-.7,gToAD=0,gToDA=0,gAccAct=0,gAccPas=0,gToPas=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita0b0g0d2o2<-mle2(full_ll,start=list(dTo=0,dAcc=0,dToAD=0,dToDA=0,dAccAct=0,dAccPas=0,dToPas=0,
                                       orderTo=0,orderAcc=0,
                                       orderToAD=0,orderToDA=0,orderAccAct=0,orderAccPas=0,orderToPas=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita0b0g2d0o2<-mle2(full_ll,start=list(gTo=-1.4,gAcc=-.7,gToAD=0,gToDA=0,gAccAct=0,gAccPas=0,gToPas=0,
                                       orderTo=0,orderAcc=0,
                                       orderToAD=0,orderToDA=0,orderAccAct=0,orderAccPas=0,orderToPas=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita0b0g2d2o0<-mle2(full_ll,start=list(gTo=-1.4,gAcc=-.7,gToAD=0,gToDA=0,gAccAct=0,gAccPas=0,gToPas=0,
                                       dTo=0,dAcc=0,dToAD=0,dToDA=0,dAccAct=0,dAccPas=0,dToPas=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita0b2g0d0o2<-mle2(full_ll,start=list(bTo=3.9,bAcc=2.7,bToAD=0,bToDA=0,bAccAct=0,bAccPas=0,bToPas=0,
                                       orderTo=0,orderAcc=0,
                                       orderToAD=0,orderToDA=0,orderAccAct=0,orderAccPas=0,orderToPas=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita0b2g0d2o0<-mle2(full_ll,start=list(bTo=3.9,bAcc=2.7,bToAD=0,bToDA=0,bAccAct=0,bAccPas=0,bToPas=0,
                                       dTo=0,dAcc=0,dToAD=0,dToDA=0,dAccAct=0,dAccPas=0,dToPas=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita0b2g2d0o0<-mle2(full_ll,start=list(bTo=3.9,bAcc=2.7,bToAD=0,bToDA=0,bAccAct=0,bAccPas=0,bToPas=0,
                                       gTo=-1.4,gAcc=-.7,gToAD=0,gToDA=0,gAccAct=0,gAccPas=0,gToPas=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2b0g0d0o2<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       orderTo=0,orderAcc=0,
                                       orderToAD=0,orderToDA=0,orderAccAct=0,orderAccPas=0,orderToPas=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2b0g0d2o0<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       dTo=0,dAcc=0,dToAD=0,dToDA=0,dAccAct=0,dAccPas=0,dToPas=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2b0g2d0o0<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       gTo=-1.4,gAcc=-.7,gToAD=0,gToDA=0,gAccAct=0,gAccPas=0,gToPas=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2b2g0d0o0<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,bAcc=2.7,bToAD=0,bToDA=0,bAccAct=0,bAccPas=0,bToPas=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2b0g0d0o0<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita0b2g0d0o0<-mle2(full_ll,start=list(bTo=3.9,bAcc=2.7,bToAD=0,bToDA=0,bAccAct=0,bAccPas=0,bToPas=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita0b0g2d0o0<-mle2(full_ll,start=list(gTo=-1.4,gAcc=-.7,gToAD=0,gToDA=0,gAccAct=0,gAccPas=0,gToPas=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita0b0g0d2o0<-mle2(full_ll,start=list(dTo=0,dAcc=0,dToAD=0,dToDA=0,dAccAct=0,dAccPas=0,dToPas=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita0b0g0d0o2<-mle2(full_ll,start=list(orderTo=0,orderAcc=0,
                                       orderToAD=0,orderToDA=0,orderAccAct=0,orderAccPas=0,orderToPas=0),
                    control=list(trace=4,REPORT=5,maxit=1000))

fita1b1g1d1o1<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,
                                       bTo=3.9,bAcc=2.7,bToAD=0,
                                       gTo=-1.4,gAcc=-.7,
                                       dTo=0,dAcc=0,
                                       orderTo=0,orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita0b1g1d1o1<-mle2(full_ll,start=list(bTo=3.9,bAcc=2.7,bToAD=0,
                                       gTo=-1.4,gAcc=-.7,
                                       dTo=0,dAcc=0,
                                       orderTo=0,orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita1b0g1d1o1<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,
                                       gTo=-1.4,gAcc=-.7,
                                       dTo=0,dAcc=0,
                                       orderTo=0,orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita1b1g0d1o1<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,
                                       bTo=3.9,bAcc=2.7,bToAD=0,
                                       dTo=0,dAcc=0,
                                       orderTo=0,orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita1b1g1d0o1<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,
                                       bTo=3.9,bAcc=2.7,bToAD=0,
                                       gTo=-1.4,gAcc=-.7,
                                       orderTo=0,orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita1b1g1d1o0<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,
                                       bTo=3.9,bAcc=2.7,bToAD=0,
                                       gTo=-1.4,gAcc=-.7,
                                       dTo=0,dAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita0b0g1d1o1<-mle2(full_ll,start=list(gTo=-1.4,gAcc=-.7,
                                       dTo=0,dAcc=0,
                                       orderTo=0,orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita0b1g0d1o1<-mle2(full_ll,start=list(bTo=3.9,bAcc=2.7,bToAD=0,
                                       dTo=0,dAcc=0,
                                       orderTo=0,orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita0b1g1d0o1<-mle2(full_ll,start=list(bTo=3.9,bAcc=2.7,bToAD=0,
                                       gTo=-1.4,gAcc=-.7,
                                       orderTo=0,orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita0b1g1d1o0<-mle2(full_ll,start=list(bTo=3.9,bAcc=2.7,bToAD=0,
                                       gTo=-1.4,gAcc=-.7,
                                       dTo=0,dAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita1b0g0d1o1<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,
                                       dTo=0,dAcc=0,
                                       orderTo=0,orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita1b0g1d0o1<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,
                                       gTo=-1.4,gAcc=-.7,
                                       orderTo=0,orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita1b0g1d1o0<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,
                                       gTo=-1.4,gAcc=-.7,
                                       dTo=0,dAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita1b1g0d0o1<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,
                                       bTo=3.9,bAcc=2.7,bToAD=0,
                                       orderTo=0,orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita1b1g0d1o0<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,
                                       bTo=3.9,bAcc=2.7,bToAD=0,
                                       dTo=0,dAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita1b1g1d0o0<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,
                                       bTo=3.9,bAcc=2.7,bToAD=0,
                                       gTo=-1.4,gAcc=-.7),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita0b0g0d1o1<-mle2(full_ll,start=list(dTo=0,dAcc=0,
                                       orderTo=0,orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita0b0g1d0o1<-mle2(full_ll,start=list(gTo=-1.4,gAcc=-.7,
                                       orderTo=0,orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita0b0g1d1o0<-mle2(full_ll,start=list(gTo=-1.4,gAcc=-.7,
                                       dTo=0,dAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita0b1g0d0o1<-mle2(full_ll,start=list(bTo=3.9,bAcc=2.7,bToAD=0,
                                       orderTo=0,orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita0b1g0d1o0<-mle2(full_ll,start=list(bTo=3.9,bAcc=2.7,bToAD=0,
                                       dTo=0,dAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita0b1g1d0o0<-mle2(full_ll,start=list(bTo=3.9,bAcc=2.7,bToAD=0,
                                       gTo=-1.4,gAcc=-.7),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita1b0g0d0o1<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,
                                       orderTo=0,orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita1b0g0d1o0<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,
                                       dTo=0,dAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita1b0g1d0o0<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,
                                       gTo=-1.4,gAcc=-.7),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita1b1g0d0o0<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,
                                       bTo=3.9,bAcc=2.7,bToAD=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita1b0g0d0o0<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita0b1g0d0o0<-mle2(full_ll,start=list(bTo=3.9,bAcc=2.7,bToAD=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita0b0g1d0o0<-mle2(full_ll,start=list(gTo=-1.4,gAcc=-.7),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita0b0g0d1o0<-mle2(full_ll,start=list(dTo=0,dAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita0b0g0d0o1<-mle2(full_ll,start=list(orderTo=0,orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita0b0g0d0o0<-full_ll()

aicTab<-AIC(fita2b2g2d2o2,fita1b2g2d2o2,fita2b1g2d2o2,fita2b2g1d2o2,fita2b2g2d1o2,fita2b2g2d2o1,fita1b1g2d2o2,fita1b2g1d2o2,fita1b2g2d1o2,fita1b2g2d2o1,fita2b1g1d2o2,fita2b1g2d1o2,fita2b1g2d2o1,fita2b2g1d1o2,fita2b2g1d2o1,fita2b2g2d1o1,fita1b1g1d2o2,fita1b1g2d1o2,fita1b1g2d2o1,fita1b2g1d1o2,fita1b2g1d2o1,fita1b2g2d1o1,fita2b1g1d1o2,fita2b1g1d2o1,fita2b1g2d1o1,fita2b2g1d1o1,fita2b1g1d1o1,fita1b2g1d1o1,fita1b1g2d1o1,fita1b1g1d2o1,fita1b1g1d1o2,fita0b2g2d2o2,fita2b0g2d2o2,fita2b2g0d2o2,fita2b2g2d0o2,fita2b2g2d2o0,fita0b0g2d2o2,fita0b2g0d2o2,fita0b2g2d0o2,fita0b2g2d2o0,fita2b0g0d2o2,fita2b0g2d0o2,fita2b0g2d2o0,fita2b2g0d0o2,fita2b2g0d2o0,fita2b2g2d0o0,fita0b0g0d2o2,fita0b0g2d0o2,fita0b0g2d2o0,fita0b2g0d0o2,fita0b2g0d2o0,fita0b2g2d0o0,fita2b0g0d0o2,fita2b0g0d2o0,fita2b0g2d0o0,fita2b2g0d0o0,fita2b0g0d0o0,fita0b2g0d0o0,fita0b0g2d0o0,fita0b0g0d2o0,fita0b0g0d0o2,fita1b1g1d1o1,fita0b1g1d1o1,fita1b0g1d1o1,fita1b1g0d1o1,fita1b1g1d0o1,fita1b1g1d1o0,fita0b0g1d1o1,fita0b1g0d1o1,fita0b1g1d0o1,fita0b1g1d1o0,fita1b0g0d1o1,fita1b0g1d0o1,fita1b0g1d1o0,fita1b1g0d0o1,fita1b1g0d1o0,fita1b1g1d0o0,fita0b0g0d1o1,fita0b0g1d0o1,fita0b0g1d1o0,fita0b1g0d0o1,fita0b1g0d1o0,fita0b1g1d0o0,fita1b0g0d0o1,fita1b0g0d1o0,fita1b0g1d0o0,fita1b1g0d0o0,fita1b0g0d0o0,fita0b1g0d0o0,fita0b0g1d0o0,fita0b0g0d1o0,fita0b0g0d0o1)
aicTab<-rbind(aicTab,c(2*fita0b0g0d0o0,0))
bicTab<-AIC(fita2b2g2d2o2,fita1b2g2d2o2,fita2b1g2d2o2,fita2b2g1d2o2,fita2b2g2d1o2,fita2b2g2d2o1,fita1b1g2d2o2,fita1b2g1d2o2,fita1b2g2d1o2,fita1b2g2d2o1,fita2b1g1d2o2,fita2b1g2d1o2,fita2b1g2d2o1,fita2b2g1d1o2,fita2b2g1d2o1,fita2b2g2d1o1,fita1b1g1d2o2,fita1b1g2d1o2,fita1b1g2d2o1,fita1b2g1d1o2,fita1b2g1d2o1,fita1b2g2d1o1,fita2b1g1d1o2,fita2b1g1d2o1,fita2b1g2d1o1,fita2b2g1d1o1,fita2b1g1d1o1,fita1b2g1d1o1,fita1b1g2d1o1,fita1b1g1d2o1,fita1b1g1d1o2,fita0b2g2d2o2,fita2b0g2d2o2,fita2b2g0d2o2,fita2b2g2d0o2,fita2b2g2d2o0,fita0b0g2d2o2,fita0b2g0d2o2,fita0b2g2d0o2,fita0b2g2d2o0,fita2b0g0d2o2,fita2b0g2d0o2,fita2b0g2d2o0,fita2b2g0d0o2,fita2b2g0d2o0,fita2b2g2d0o0,fita0b0g0d2o2,fita0b0g2d0o2,fita0b0g2d2o0,fita0b2g0d0o2,fita0b2g0d2o0,fita0b2g2d0o0,fita2b0g0d0o2,fita2b0g0d2o0,fita2b0g2d0o0,fita2b2g0d0o0,fita2b0g0d0o0,fita0b2g0d0o0,fita0b0g2d0o0,fita0b0g0d2o0,fita0b0g0d0o2,fita1b1g1d1o1,fita0b1g1d1o1,fita1b0g1d1o1,fita1b1g0d1o1,fita1b1g1d0o1,fita1b1g1d1o0,fita0b0g1d1o1,fita0b1g0d1o1,fita0b1g1d0o1,fita0b1g1d1o0,fita1b0g0d1o1,fita1b0g1d0o1,fita1b0g1d1o0,fita1b1g0d0o1,fita1b1g0d1o0,fita1b1g1d0o0,fita0b0g0d1o1,fita0b0g1d0o1,fita0b0g1d1o0,fita0b1g0d0o1,fita0b1g0d1o0,fita0b1g1d0o0,fita1b0g0d0o1,fita1b0g0d1o0,fita1b0g1d0o0,fita1b1g0d0o0,fita1b0g0d0o0,fita0b1g0d0o0,fita0b0g1d0o0,fita0b0g0d1o0,fita0b0g0d0o1,k=log(dim(true.data)[1]))
bicTab<-rbind(bicTab,c(2*fita0b0g0d0o0,0))

names <- c('fita2b2g2d2o2','gfita1b2g2d2o2','fita2b1g2d2o2','fita2b2g1d2o2','fita2b2g2d1o2','fita2b2g2d2o1','fita1b1g2d2o2','fita1b2g1d2o2','fita1b2g2d1o2','fita1b2g2d2o1','fita2b1g1d2o2','fita2b1g2d1o2','fita2b1g2d2o1','fita2b2g1d1o2','fita2b2g1d2o1','fita2b2g2d1o1','fita1b1g1d2o2','fita1b1g2d1o2','fita1b1g2d2o1','fita1b2g1d1o2','fita1b2g1d2o1','fita1b2g2d1o1','fita2b1g1d1o2','fita2b1g1d2o1','fita2b1g2d1o1','fita2b2g1d1o1','fita2b1g1d1o1','fita1b2g1d1o1','fita1b1g2d1o1','fita1b1g1d2o1','fita1b1g1d1o2','fita0b2g2d2o2','fita2b0g2d2o2','fita2b2g0d2o2','fita2b2g2d0o2','fita2b2g2d2o0','fita0b0g2d2o2','fita0b2g0d2o2','fita0b2g2d0o2','fita0b2g2d2o0','fita2b0g0d2o2','fita2b0g2d0o2','fita2b0g2d2o0','fita2b2g0d0o2','fita2b2g0d2o0','fita2b2g2d0o0','fita0b0g0d2o2','fita0b0g2d0o2','fita0b0g2d2o0','fita0b2g0d0o2','fita0b2g0d2o0','fita0b2g2d0o0','fita2b0g0d0o2','fita2b0g0d2o0','fita2b0g2d0o0','fita2b2g0d0o0','fita2b0g0d0o0','fita0b2g0d0o0','fita0b0g2d0o0','fita0b0g0d2o0','fita0b0g0d0o2','fita1b1g1d1o1','fita0b1g1d1o1','fita1b0g1d1o1','fita1b1g0d1o1','fita1b1g1d0o1','fita1b1g1d1o0','fita0b0g1d1o1','fita0b1g0d1o1','fita0b1g1d0o1','fita0b1g1d1o0','fita1b0g0d1o1','fita1b0g1d0o1','fita1b0g1d1o0','fita1b1g0d0o1','fita1b1g0d1o0','fita1b1g1d0o0','fita0b0g0d1o1','fita0b0g1d0o1','fita0b0g1d1o0','fita0b1g0d0o1','fita0b1g0d1o0','fita0b1g1d0o0','fita1b0g0d0o1','fita1b0g0d1o0','fita1b0g1d0o0','fita1b1g0d0o0','fita1b0g0d0o0','fita0b1g0d0o0','fita0b0g1d0o0','fita0b0g0d1o0','fita0b0g0d0o1','fita0b0g0d0o0')
rownames(aicTab)<-names
aicTab
names[which.min(aicTab[,1])]
rownames(bicTab)<-names
bicTab
names[which.min(bicTab[,1])]

fita2bTg1d1o1<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,
                                       gTo=-1.4,gAcc=-.7,
                                       dTo=0,dAcc=0,
                                       orderTo=0,orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2b1gTd1o1<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,bAcc=2.7,
                                       gTo=-1.4,
                                       dTo=0,dAcc=0,
                                       orderTo=0,orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2b1g1dTo1<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,bAcc=2.7,
                                       gTo=-1.4,gAcc=-.7,
                                       dTo=0,
                                       orderTo=0,orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2b1g1d1oT<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,bAcc=2.7,
                                       gTo=-1.4,gAcc=-.7,
                                       dTo=0,dAcc=0,
                                       orderTo=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2bTgTd1o1<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,
                                       gTo=-1.4,
                                       dTo=0,dAcc=0,
                                       orderTo=0,orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2bTg1dTo1<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,
                                       gTo=-1.4,gAcc=-.7,
                                       dTo=0,
                                       orderTo=0,orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2bTg1d1oT<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,
                                       gTo=-1.4,gAcc=-.7,
                                       dTo=0,dAcc=0,
                                       orderTo=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2b1gTdTo1<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,bAcc=2.7,
                                       gTo=-1.4,
                                       dTo=0,
                                       orderTo=0,orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2b1gTd1oT<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,bAcc=2.7,
                                       gTo=-1.4,
                                       dTo=0,dAcc=0,
                                       orderTo=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2b1g1dToT<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,bAcc=2.7,
                                       gTo=-1.4,gAcc=-.7,
                                       dTo=0,
                                       orderTo=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2bTgTdTo1<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,
                                       gTo=-1.4,
                                       dTo=0,
                                       orderTo=0,orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2bTgTd1oT<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,
                                       gTo=-1.4,
                                       dTo=0,dAcc=0,
                                       orderTo=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2bTg1dToT<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,
                                       gTo=-1.4,gAcc=-.7,
                                       dTo=0,
                                       orderTo=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2b1gTdToT<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,bAcc=2.7,
                                       gTo=-1.4,
                                       dTo=0,
                                       orderTo=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2bTgTdToT<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,
                                       gTo=-1.4,
                                       dTo=0,
                                       orderTo=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2bAg1d1o1<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bAcc=2.7,
                                       gTo=-1.4,gAcc=-.7,
                                       dTo=0,dAcc=0,
                                       orderTo=0,orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2b1gAd1o1<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,bAcc=2.7,
                                       gAcc=-.7,
                                       dTo=0,dAcc=0,
                                       orderTo=0,orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2b1g1dAo1<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,bAcc=2.7,
                                       gTo=-1.4,gAcc=-.7,
                                       dAcc=0,
                                       orderTo=0,orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2b1g1d1oA<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,bAcc=2.7,
                                       gTo=-1.4,gAcc=-.7,
                                       dTo=0,dAcc=0,
                                       orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2bAgAd1o1<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bAcc=2.7,
                                       gAcc=-.7,
                                       dTo=0,dAcc=0,
                                       orderTo=0,orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2bAg1dAo1<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bAcc=2.7,
                                       gTo=-1.4,gAcc=-.7,
                                       dAcc=0,
                                       orderTo=0,orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2bAg1d1oA<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bAcc=2.7,
                                       gTo=-1.4,gAcc=-.7,
                                       dTo=0,dAcc=0,
                                       orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2b1gAdAo1<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,bAcc=2.7,
                                       gAcc=-.7,
                                       dAcc=0,
                                       orderTo=0,orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2b1gAd1oA<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,bAcc=2.7,
                                       gAcc=-.7,
                                       dTo=0,dAcc=0,
                                       orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2b1g1dAoA<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,bAcc=2.7,
                                       gTo=-1.4,gAcc=-.7,
                                       dAcc=0,
                                       orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2bAgAdAo1<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bAcc=2.7,
                                       gAcc=-.7,
                                       dAcc=0,
                                       orderTo=0,orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2bAgAd1oA<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bAcc=2.7,
                                       gAcc=-.7,
                                       dTo=0,dAcc=0,
                                       orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2bAg1dAoA<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bAcc=2.7,
                                       gTo=-1.4,gAcc=-.7,
                                       dAcc=0,
                                       orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2b1gAdAoA<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,bAcc=2.7,
                                       gAcc=-.7,
                                       dAcc=0,
                                       orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2bAgAdAoA<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bAcc=2.7,
                                       gAcc=-.7,
                                       dAcc=0,
                                       orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2bTgAd1o1<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,
                                       gAcc=-.7,
                                       dTo=0,dAcc=0,
                                       orderTo=0,orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2bTg1dAo1<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,
                                       gTo=-1.4,gAcc=-.7,
                                       dAcc=0,
                                       orderTo=0,orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2bTg1d1oA<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,
                                       gTo=-1.4,gAcc=-.7,
                                       dTo=0,dAcc=0,
                                       orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2bTgTdAo1<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,
                                       gTo=-1.4,
                                       dAcc=0,
                                       orderTo=0,orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2bTgTd1oA<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,
                                       gTo=-1.4,
                                       dTo=0,dAcc=0,
                                       orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2bTg1dToA<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,
                                       gTo=-1.4,gAcc=-.7,
                                       dTo=0,
                                       orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2bAgTd1o1<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bAcc=2.7,
                                       gTo=-1.4,
                                       dTo=0,dAcc=0,
                                       orderTo=0,orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2bAg1dTo1<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bAcc=2.7,
                                       gTo=-1.4,gAcc=-.7,
                                       dTo=0,
                                       orderTo=0,orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2bAg1d1oT<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bAcc=2.7,
                                       gTo=-1.4,gAcc=-.7,
                                       dTo=0,dAcc=0,
                                       orderTo=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2b1gAdTo1<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,bAcc=2.7,
                                       gAcc=-.7,
                                       dTo=0,
                                       orderTo=0,orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2b1gAd1oT<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,bAcc=2.7,
                                       gAcc=-.7,
                                       dTo=0,dAcc=0,
                                       orderTo=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2b1g1dAoT<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,bAcc=2.7,
                                       gTo=-1.4,gAcc=-.7,
                                       dAcc=0,
                                       orderTo=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2bTgAdTo1<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,
                                       gAcc=-.7,
                                       dTo=0,
                                       orderTo=0,orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2bTgAd1oT<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,
                                       gAcc=-.7,
                                       dTo=0,dAcc=0,
                                       orderTo=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2bTgAdAo1<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,
                                       gAcc=-.7,
                                       dAcc=0,
                                       orderTo=0,orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2bTgAd1oA<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,
                                       gAcc=-.7,
                                       dTo=0,dAcc=0,
                                       orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2b1gTdToA<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,bAcc=2.7,
                                       gTo=-1.4,
                                       dTo=0,
                                       orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2b1gTdAoT<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,bAcc=2.7,
                                       gTo=-1.4,
                                       dAcc=0,
                                       orderTo=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2b1gTdAoA<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,bAcc=2.7,
                                       gTo=-1.4,
                                       dAcc=0,
                                       orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2bAgTdTo1<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bAcc=2.7,
                                       gTo=-1.4,
                                       dTo=0,
                                       orderTo=0,orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2bAgTd1oT<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bAcc=2.7,
                                       gTo=-1.4,
                                       dTo=0,dAcc=0,
                                       orderTo=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2bAgTdAo1<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bAcc=2.7,
                                       gTo=-1.4,
                                       dAcc=0,
                                       orderTo=0,orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2bAgTd1oA<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bAcc=2.7,
                                       gTo=-1.4,
                                       dTo=0,dAcc=0,
                                       orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2bAgAdTo1<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bAcc=2.7,
                                       gAcc=-.7,
                                       dTo=0,
                                       orderTo=0,orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2bAgAd1oT<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bAcc=2.7,
                                       gAcc=-.7,
                                       dTo=0,dAcc=0,
                                       orderTo=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2b1gAdToT<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,bAcc=2.7,
                                       gAcc=-.7,
                                       dTo=0,
                                       orderTo=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2b1gAdToA<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,bAcc=2.7,
                                       gAcc=-.7,
                                       dTo=0,
                                       orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2b1gAdAoT<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,bAcc=2.7,
                                       gAcc=-.7,
                                       dAcc=0,
                                       orderTo=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2bTgTdToA<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,
                                       gTo=-1.4,
                                       dTo=0,
                                       orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2bTgTdAoT<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,
                                       gTo=-1.4,
                                       dAcc=0,
                                       orderTo=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2bTgAdToT<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,
                                       gAcc=-.7,
                                       dTo=0,
                                       orderTo=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2bAgTdToT<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bAcc=2.7,
                                       gTo=-1.4,
                                       dTo=0,
                                       orderTo=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2bTgAdAoT<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,
                                       gAcc=-.7,
                                       dAcc=0,
                                       orderTo=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2bTgAdToA<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,
                                       gTo=-1.4,
                                       dAcc=0,
                                       orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2bTgTdAoA<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,
                                       gTo=-1.4,
                                       dAcc=0,
                                       orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2bAgTdToA<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bAcc=2.7,
                                       gTo=-1.4,
                                       dTo=0,
                                       orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2bAgTdAoT<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bAcc=2.7,
                                       gTo=-1.4,
                                       dAcc=0,
                                       orderTo=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2bAgAdToT<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bAcc=2.7,
                                       gAcc=-.7,
                                       dTo=0,
                                       orderTo=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2bTgAdAoA<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,
                                       gAcc=-.7,
                                       dAcc=0,
                                       orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2bAgTdAoA<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bAcc=2.7,
                                       gTo=-1.4,
                                       dAcc=0,
                                       orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2bAgAdToA<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bAcc=2.7,
                                       gAcc=-.7,
                                       dTo=0,
                                       orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))
fita2bAgAdAoT<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bAcc=2.7,
                                       gAcc=-.7,
                                       dAcc=0,
                                       orderTo=0),
                    control=list(trace=4,REPORT=5,maxit=1000))

newAICTab <- AIC(fita2b1g1d1o1,fita2bTg1d1o1,fita2b1gTd1o1,fita2b1g1dTo1,fita2b1g1d1oT,fita2bTgTd1o1,fita2bTg1dTo1,fita2bTg1d1oT,fita2b1gTdTo1,fita2b1gTd1oT,fita2b1g1dToT,fita2bTgTdTo1,fita2bTgTd1oT,fita2bTg1dToT,fita2b1gTdToT,fita2bTgTdToT,fita2bAg1d1o1,fita2b1gAd1o1,fita2b1g1dAo1,fita2b1g1d1oA,fita2bAgAd1o1,fita2bAg1dAo1,fita2bAg1d1oA,fita2b1gAdAo1,fita2b1gAd1oA,fita2b1g1dAoA,fita2bAgAdAo1,fita2bAgAd1oA,fita2bAg1dAoA,fita2b1gAdAoA,fita2bAgAdAoA,fita2bTgAd1o1,fita2bTg1dAo1,fita2bTg1d1oA,fita2bTg1dToA,fita2bAgTd1o1,fita2bAg1dTo1,fita2bAg1d1oT,fita2b1gAdTo1,fita2b1gAd1oT,fita2b1g1dAoT,fita2bTgTdAo1,fita2bTgTd1oA,fita2bTgAdTo1,fita2bTgAd1oT,fita2bTgAdAo1,fita2bTgAd1oA,fita2b1gTdToA,fita2b1gTdAoT,fita2b1gTdAoA,fita2bAgTdTo1,fita2bAgTd1oT,fita2bAgTdAo1,fita2bAgTd1oA,fita2bAgAdTo1,fita2bAgAd1oT,fita2b1gAdToT,fita2b1gAdToA,fita2b1gAdAoT,fita2bTgTdToA,fita2bTgTdAoT,fita2bTgAdToT,fita2bAgTdToT,fita2bTgAdAoT,fita2bTgAdToA,fita2bTgTdAoA,fita2bAgTdToA,fita2bAgTdAoT,fita2bAgAdToT,fita2bTgAdAoA,fita2bAgTdAoA,fita2bAgAdToA,fita2bAgAdAoT)
newNames <- c('fita2b1g1d1o1','fita2bTg1d1o1','fita2b1gTd1o1','fita2b1g1dTo1','fita2b1g1d1oT','fita2bTgTd1o1','fita2bTg1dTo1','fita2bTg1d1oT','fita2b1gTdTo1','fita2b1gTd1oT','fita2b1g1dToT','fita2bTgTdTo1','fita2bTgTd1oT','fita2bTg1dToT','fita2b1gTdToT','fita2bTgTdToT','fita2bAg1d1o1','fita2b1gAd1o1','fita2b1g1dAo1','fita2b1g1d1oA','fita2bAgAd1o1','fita2bAg1dAo1','fita2bAg1d1oA','fita2b1gAdAo1','fita2b1gAd1oA','fita2b1g1dAoA','fita2bAgAdAo1','fita2bAgAd1oA','fita2bAg1dAoA','fita2b1gAdAoA','fita2bAgAdAoA','fita2bTgAd1o1','fita2bTg1dAo1','fita2bTg1d1oA','fita2bTg1dToA','fita2bAgTd1o1','fita2bAg1dTo1','fita2bAg1d1oT','fita2b1gAdTo1','fita2b1gAd1oT','fita2b1g1dAoT','fita2bTgTdAo1','fita2bTgTd1oA','fita2bTgAdTo1','fita2bTgAd1oT','fita2bTgAdAo1','fita2bTgAd1oA','fita2b1gTdToA','fita2b1gTdAoT','fita2b1gTdAoA','fita2bAgTdTo1','fita2bAgTd1oT','fita2bAgTdAo1','fita2bAgTd1oA','fita2bAgAdTo1','fita2bAgAd1oT','fita2b1gAdToT','fita2b1gAdToA','fita2b1gAdAoT','fita2bTgTdToA','fita2bTgTdAoT','fita2bTgAdToT','fita2bAgTdToT','fita2bTgAdAoT','fita2bTgAdToA','fita2bTgTdAoA','fita2bAgTdToA','fita2bAgTdAoT','fita2bAgAdToT','fita2bTgAdAoA','fita2bAgTdAoA','fita2bAgAdToA','fita2bAgAdAoT')
rownames(newAICTab)<-newNames

fita2b1gTd0oA<-mle2(full_ll,start=list(aTo=.6,aAcc=-3.1,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,
                                       bTo=3.9,bAcc=2.7,
                                       gTo=-1.4,
                                       orderAcc=0),
                    control=list(trace=4,REPORT=5,maxit=1000))

aicTab
names[which.min(aicTab[,1])]

newAICTab
newNames[which.min(newAICTab[,1])]

pred_ll<-function(aTo=0,aAcc=0,aToAD=0,aToDA=0,aAccAct=0,aAccPas=0,aToPas=0,bTo=0,bAcc=0,bToAD=0,bToDA=0,bAccAct=0,bAccPas=0,bToPas=0,gTo=0,gAcc=0,gToAD=0,gToDA=0,gAccAct=0,gAccPas=0,gToPas=0,dTo=0,dAcc=0,dToAD=0,dToDA=0,dAccAct=0,dAccPas=0,dToPas=0,orderTo=0,orderAcc=0,orderToAD=0,orderToDA=0,orderAccAct=0,orderAccPas=0,orderToPas=0){
  p1<-((1-(1-(ord+orderTo+orderToAD))*pdata1$iodo)/(1+exp(-(aTo+aToAD+(bTo+bToAD)*pdata1$x+(gTo+gToAD)*pdata1$iosum+(dTo+dToAD)*pdata1$x*pdata1$iosum))))
  p2<-((1-(1-(ord+orderTo+orderToDA))*pdata2$iodo)/(1+exp(-(aTo+aToDA+(bTo+bToDA)*pdata2$x+(gTo+gToDA)*pdata2$iosum+(dTo+dToDA)*pdata2$x*pdata2$iosum))))*
    ((1-(1-(ord+orderAcc+orderAccAct))*pdata2$iopro)-((1-(1-(ord+orderAcc+orderAccAct))*pdata2$iopro)/(1+exp(-(aAcc+aAccAct+(bAcc+bAccAct)*pdata2$x+(gAcc+gAccAct)*pdata2$iosum+(dAcc+dAccAct)*pdata2$x*pdata2$iosum)))))*pdata2$donoun
  p3<-((1-(1-(ord+orderAcc+orderAccPas))*pdata3$iopro)/(1+exp(-(aAcc+aAccPas+(bAcc+bAccPas)*pdata3$x+(gAcc+gAccPas)*pdata3$iosum+(dAcc+dAccPas)*pdata3$x*pdata3$iosum))))*pdata3$donoun
  p4<-((1-(1-(ord+orderTo+orderToPas))*pdata4$iopro)/(1+exp(-(aTo+aToPas+(bTo+bToPas)*pdata4$x+(gTo+gToPas)*pdata4$iosum+(dTo+dToPas)*pdata4$x*pdata4$iosum))))
  results <- data.frame(p1=p1,p2=p2,p3=p3,p4=p4)
}


pdata1<-data.frame(Year=rep(seq(650,1950),4),iosum=c(rep(1,1301),rep(1,1301),rep(-1,1301),rep(-1,1301)),dosum=c(rep(1,1301),rep(-1,1301),rep(1,1301),rep(-1,1301)),iopro=c(rep(1,1301),rep(1,1301),rep(0,1301),rep(0,1301)),donoun=c(rep(0,1301),rep(1,1301),rep(0,1301),rep(1,1301)),Type='AD')
pdata1$iodo<-factor(pdata1$iosum+pdata1$dosum)
levels(pdata1$iodo)<-c('0','0','1')
pdata1$iodo<-as.numeric(as.character(pdata1$iodo))
pdata1$x<-(pdata1$Year-mean(joint.data$Year))/sd(joint.data$Year)
pdata2<-data.frame(Year=rep(seq(650,1950),4),iosum=c(rep(1,1301),rep(1,1301),rep(-1,1301),rep(-1,1301)),dosum=c(rep(1,1301),rep(-1,1301),rep(1,1301),rep(-1,1301)),iopro=c(rep(1,1301),rep(1,1301),rep(0,1301),rep(0,1301)),donoun=c(rep(0,1301),rep(1,1301),rep(0,1301),rep(1,1301)),Type='DA')
pdata2$iodo<-factor(pdata2$iosum+pdata2$dosum)
levels(pdata2$iodo)<-c('0','0','1')
pdata2$iodo<-as.numeric(as.character(pdata2$iodo))
pdata2$x<-(pdata2$Year-mean(joint.data$Year))/sd(joint.data$Year)
pdata3<-data.frame(Year=rep(seq(650,1950),4),iosum=c(rep(1,1301),rep(1,1301),rep(-1,1301),rep(-1,1301)),dosum=c(rep(1,1301),rep(-1,1301),rep(1,1301),rep(-1,1301)),iopro=c(rep(1,1301),rep(1,1301),rep(0,1301),rep(0,1301)),donoun=c(rep(0,1301),rep(1,1301),rep(0,1301),rep(1,1301)),Type='Passive')
pdata3$iodo<-factor(pdata3$iosum+pdata3$dosum)
levels(pdata3$iodo)<-c('0','0','1')
pdata3$iodo<-as.numeric(as.character(pdata3$iodo))
pdata3$x<-(pdata3$Year-mean(joint.data$Year))/sd(joint.data$Year)
pdata4<-data.frame(Year=rep(seq(650,1950),4),iosum=c(rep(1,1301),rep(1,1301),rep(-1,1301),rep(-1,1301)),dosum=c(rep(1,1301),rep(-1,1301),rep(1,1301),rep(-1,1301)),iopro=c(rep(1,1301),rep(1,1301),rep(0,1301),rep(0,1301)),donoun=c(rep(0,1301),rep(1,1301),rep(0,1301),rep(1,1301)),Type='Passive To')
pdata4$iodo<-factor(pdata4$iosum+pdata4$dosum)
levels(pdata4$iodo)<-c('0','0','1')
pdata4$iodo<-as.numeric(as.character(pdata4$iodo))
pdata4$x<-(pdata4$Year-mean(joint.data$Year))/sd(joint.data$Year)

fullcoef<-as.list(coef(fita2b1g1d1o1))
fullpred<-as.data.frame(pred_ll(aTo=fullcoef$aTo,aAcc=fullcoef$aAcc,
                  aToAD=fullcoef$aToAD,aToDA=fullcoef$aToDA,aAccAct=fullcoef$aAccAct,aAccPas=fullcoef$aAccPas,aToPas=fullcoef$aToPas,
                  bTo=fullcoef$bTo,bAcc=fullcoef$bAcc,gTo=fullcoef$gTo,gAcc=fullcoef$gAcc,dTo=fullcoef$dTo,dAcc=fullcoef$dAcc,
                  orderTo=fullcoef$orderTo,orderAcc=fullcoef$orderAcc))
pdata1$full<-fullpred$p1
pdata2$full<-fullpred$p2
pdata3$full<-fullpred$p3
pdata4$full<-fullpred$p4

smallcoef<-as.list(coef(fita2b1gTdAoA))
smallpred<-as.data.frame(pred_ll(aTo=smallcoef$aTo,aAcc=smallcoef$aAcc,
                   aToAD=smallcoef$aToAD,aToDA=smallcoef$aToDA,aAccAct=smallcoef$aAccAct,aAccPas=smallcoef$aAccPas,aToPas=smallcoef$aToPas,
                   bTo=smallcoef$bTo,bAcc=smallcoef$bAcc,gTo=smallcoef$gTo,dAcc=smallcoef$dAcc,
                   orderAcc=smallcoef$orderAcc))
pdata1$small<-smallpred$p1
pdata2$small<-smallpred$p2
pdata3$small<-smallpred$p3
pdata4$small<-smallpred$p4

finalcoef<-as.list(coef(fita2b1gTd0oA))
finalpred<-as.data.frame(pred_ll(aTo=smallcoef$aTo,aAcc=smallcoef$aAcc,
                                 aToAD=smallcoef$aToAD,aToDA=smallcoef$aToDA,aAccAct=smallcoef$aAccAct,aAccPas=smallcoef$aAccPas,aToPas=smallcoef$aToPas,
                                 bTo=smallcoef$bTo,bAcc=smallcoef$bAcc,gTo=smallcoef$gTo,
                                 orderAcc=smallcoef$orderAcc))
pdata1$final<-finalpred$p1
pdata2$final<-finalpred$p2
pdata3$final<-finalpred$p3
pdata4$final<-finalpred$p4

pred.data<-as.data.frame(rbind(pdata1,pdata2,pdata3,pdata4))
pred.data$DO<-factor(pred.data$donoun)
levels(pred.data$DO)<-c('DOPronoun','DONoun')
pred.data$IO<-factor(pred.data$iopro)
levels(pred.data$IO)<-c('IONoun','IOPronoun')

real.data$DO<-factor(real.data$donoun)
levels(real.data$DO)<-c('DOPronoun','DONoun')
real.data$IO<-factor(real.data$iopro)
levels(real.data$IO)<-c('IONoun','IOPronoun')



joint.data$Bin<-cut(joint.data$Year,seq(675,1925,50),seq(700,1900,50))
joint.data$Bin<-as.numeric(as.character(joint.data$Bin))

new.data.1<-ddply(subset(joint.data,Cond==1),.(Type,Bin,IO,DO),summarize,new.val=sum(Value)/sum(!is.na(Value)),n=sum(!is.na(Value)))
new.data.2<-ddply(subset(joint.data,Cond==2),.(Type,Bin,IO,DO),summarize,new.val=sum(Value)/sum(!is.na(Value)),n=sum(!is.na(Value)))
new.data.3<-ddply(subset(joint.data,Cond==3),.(Type,Bin,IO,DO),summarize,new.val=sum(Value)/sum(!is.na(Value)),n=sum(!is.na(Value)))
new.data.3$Type<-factor(c('Passive'))
new.data.4<-ddply(subset(joint.data,Cond==4),.(Type,Bin,IO,DO),summarize,new.val=sum(Value)/sum(!is.na(Value)),n=sum(!is.na(Value)))
new.data.4$Type<-factor(c('Passive To'))
new.data<-as.data.frame(rbind(new.data.1,new.data.2,new.data.3,new.data.4))

real.data$Type<-factor(real.data$cond)
levels(real.data$Type)<-c('AD','DA','Passive','Passive To')

ggplot(pred.data,aes(Year,full,colour=IO))+geom_line(aes(linetype='Full'))+geom_line(aes(Year,small,linetype='Small'))+geom_line(aes(Year,final,linetype='Final'))+geom_point(data=new.data,aes(Bin,new.val,size=log(n,5)))+facet_grid(DO~Type)

